# Generated by Django 4.1.6 on 2023-02-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.CharField(
                choices=[
                    ("Table Reservations", "Table Reservations"),
                    ("Booth Reservations", "Booth Reservations"),
                    ("Couch Reservations", "Couch Reservations"),
                    (
                        "Private Occasion",
                        "Private Occasion",
                    ),
                ],
                default="Table Reservations",
                max_length=50,
            ),
        ),
    ]
