# Generated by Django 4.1.6 on 2023-02-17 03:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0002_alter_appointment_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Table Reservations", "Table Reservations"),
                            ("Booth Reservations", "Booth Reservations"),
                            ("Couch Reservations", "Couch Reservations"),
                            ("Private Occasion", "Private Occasion"),
                        ],
                        default="Table Reservations",
                        max_length=50,
                    ),
                ),
                ("day", models.DateField(default=datetime.datetime.now)),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("1 PM", "1 PM"),
                            ("1:30 PM", "1:30 PM"),
                            ("2 PM", "2 PM"),
                            ("2 PM", "2:30 PM"),
                            ("3 PM", "3 PM"),
                            ("3:30 PM", "3:30 PM"),
                            ("4 PM", "4 PM"),
                            ("4:30 PM", "4:30 PM"),
                            ("5 PM", "5 PM"),
                            ("5:30 PM", "5:30 PM"),
                            ("6 PM", "6 PM"),
                            ("6:30 PM", "6:30 PM"),
                            ("7 PM", "7 PM"),
                            ("7:30 PM", "7:30 PM"),
                        ],
                        default="1 PM",
                        max_length=10,
                    ),
                ),
                (
                    "time_ordered",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Appointment",),
    ]
