# Generated by Django 4.1.6 on 2023-02-17 22:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0004_rename_reservations_appointment"),
    ]

    operations = [
        migrations.RenameModel(old_name="appointment", new_name="Reservation",),
    ]
