# Generated by Django 4.1.6 on 2023-02-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_reservation_guests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="guests",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("6", "7"),
                ],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="service",
            field=models.CharField(
                choices=[
                    ("Table Reservations", "Table Reservations"),
                    ("Booth Reservations", "Booth Reservations"),
                    ("Couch Reservations", "Couch Reservations"),
                    ("Private Occasion", "Private Occasion"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
