# Generated by Django 4.1.6 on 2023-02-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_alter_reservation_guests_alter_reservation_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="service",
            field=models.CharField(
                choices=[
                    ("Table Reservations", "Table Reservations"),
                    ("Booth Reservations", "Booth Reservations"),
                    ("Couch Reservations", "Couch Reservations"),
                    ("Private Occasion", "Private Occasion"),
                ],
                default="Table Reservations",
                max_length=50,
            ),
        ),
    ]
